Create race.md
hydro-dev/hydro-dev.github.io pull request #16
Opened 2021-10-30 08:20 UTC by sosyz

添加比赛建议

2021-10-30 08:25 UTC, undefined-moe requested changes

2021-10-30 08:25 UTC, undefined-moe commented on docs/system/race.md
> +#### (1)导入
推荐使用列表语法而非四级标题

2021-10-30 08:25 UTC, undefined-moe commented on docs/system/race.md
> +​		导入完成后，检查测试数据是否存在，存在接着从导入网站处复制AC代码粘贴至网站进行测试，检查是否能够AC，如果不能AC检查题目配置文件、测试数据是否存在问题并修复。
不要使用tab。

2021-10-30 08:25 UTC, undefined-moe commented on docs/system/race.md
> +​		根据赛事规模进行服务器配置及准备备用服务器，50人规模使用2H4G腾讯云轻量服务器无压力，判题机建议两台（一台本地一台远程）或更多，注意检查前端、判题机版本一致性，可以直接都更新到最新版。
100人左右规模无需外接判题机。

2021-10-30 08:25 UTC, undefined-moe commented on docs/system/race.md
> +​		赛事题目出现问题的，进行公告及监考老师通知选手变化，赛时不建议进行重测。
重测是低优先级的。不会影响选手正常提交。建议早发现早解决。

2021-10-31 06:02 UTC, undefined-moe commented on docs/system/race.md
> +编写时间：2021年10月30日		编者：Sonui
lastUpdate和contributor可以在build阶段生成，无需标明

2021-10-31 06:03 UTC, sosyz commented on docs/system/race.md
> +编写时间：2021年10月30日		编者：Sonui
给下一届的发的忘了删了。。。

2021-10-31 06:16 UTC, undefined-moe requested changes

2021-10-31 06:16 UTC, undefined-moe commented on docs/system/race.md
> +　　根据赛事规模进行服务器配置及准备备用服务器，50人规模使用2H4G腾讯云轻量服务器无压力，判题机根据情况设置，100人左右规模无需外接判题机，更大规模根据建议两台（一台本地一台远程）或更多，注意检查前端、判题机版本一致性，可以直接都更新到最新版。
不建议本地远程混用，可能导致计时不稳定。若确要使用多评测机，建议使用完全相同的配置，且判题机上不要运行其他程序。

2021-10-31 06:16 UTC, undefined-moe commented on docs/system/race.md
> +    - 原创：编写完成后，根据出题人考察点制造测试数据，测试数据注意避免Windows和Linux下不同处理造成的错误，例如换行Windows下为`\r\n`，Linux下为`\n`，建议直接编写标答代码直接输出到文件，题目数据导入至网站后进行测试检查是否能正确通过。
建议标明 此问题只会在选手使用了基于字符的快速读入且没有正确处理 `\r` 的情况下出现

2022-09-07 16:53 UTC, closed without merging