Update FAQ.md
hydro-dev/hydro-dev.github.io pull request #21
Opened 2021-12-28 17:18 UTC by sosyz

添加自定义用户标签部分示例

2021-12-29 05:08 UTC, undefined-moe requested changes
请在PR前仔细检查。

2022-01-24 03:01 UTC, juruo888 commented
HEX 颜色不用加尖括号

2022-01-26 12:41 UTC, sosyz commented
> HEX 颜色不用加尖括号

感谢，已纠正

2022-02-25 15:37 UTC, undefined-moe commented
我还是觉得应该少说废话。

2022-02-28 07:01 UTC, closed without merging