修改端口转发教程：移除 ngrok，新增 frp 和 VPN 方案
hydro-dev/hydro-dev.github.io pull request #28
Opened 2022-03-08 05:36 UTC by Ruanxingzhi

ngrok 已经没什么人用了，修改为目前流行的 frp 方案。

新增 VPN 方案（e.g. wireguard 组网，nginx 反代）

2022-03-08 05:42 UTC, undefined-moe commented
frp 的配置较为复杂，我个人更推荐傻瓜式的 [nps](https://github.com/ehang-io/nps) 。

另，考虑到国情，大部分家宽所使用的 NAT 无法使用 wireguard 等工具打通，而 zerotier 在不自定义 moon 节点的情况下速度十分糟糕，在文中介绍的意义不大，可以留给专业用户自行探索。
本文档期望尽可能简化各操作的流程，因此在反向代理一节使用了 caddy 而非 nginx。自动化的 https 一站式方案可能更适合新手用户。

2022-03-08 05:43 UTC, undefined-moe commented
Argo tunnel 或许也是一个不错的选择。

2022-03-09 05:28 UTC, wuxianucw requested changes
待进一步讨论。

2022-03-09 05:28 UTC, wuxianucw commented on docs/install/port-forwarding.md
> +这类方案的主要思路是：首先把「位于内网的主机」与「位于公网的 VPS」组建成虚拟网络，再于 VPS 上运行反向代理服务。
方案描述较为抽象，话题比较开放，不适合详细展开，进而不太复合文档“清楚、具体”的要求。可不必详细描述而只简单略过，具体使用到的软件、配置细节留给有探索能力的用户自行尝试即可。

2022-03-09 05:28 UTC, wuxianucw commented on docs/install/port-forwarding.md
> -## ngrok
不必移除原有方案，可新增、调整顺序，给用户更多选择。

2022-10-25 15:44 UTC, pandadtdyy commented
Thanks for contributing Hydro document. But now the document about port forwarding was removed. So I close this pr.

2022-10-25 15:44 UTC, closed without merging